apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURCVENDQWUyZ0F3SUJBZ0lJTWk5Um9SY2ltZk13RFFZSktvWklodmNOQVFFTEJRQXdGVEVUTUJFR0ExVUUKQXhNS2EzVmlaWEp1WlhSbGN6QWVGdzB5TlRBeE1qUXhOREUzTkRWYUZ3MHpOVEF4TWpJeE5ESXlORFZhTUJVeApFekFSQmdOVkJBTVRDbXQxWW1WeWJtVjBaWE13Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLCkFvSUJBUUMvVy9xelJXMXlLeDBHTExZZ0loa0VITHJNUk5ZczBlYkZiM2JYUGEzeDhUTlZNajBIbjIxQjBrbmEKWDBPQkhiaFZTM1F5Vlh0RkRQaEU5YlllQWlNTWVTOWUydmozY0hzUG11NmhXV0pmejAzUWdmVjBJTFNCYmprWApLK3grb0lySXB0cDdUQ1kzalhVbmhyWjZxaS90WEV1T2xFTE9YVm9UNDRWaXJNWkRybXhpcGptais1Zlp2Z0JSCnhXVVdUcnB1Q2o0bFFxVTh3b0pSNlMwY3dpM1RJTEE5aGdkNlNtV3laUFlmZmxDRG5SZTFsS3pPV1VJdDNOdzUKcjVtSnBQMDh4RVBpS3BCODNseGQxbzdHeDNrdjczdFdPSnlBN3grZ1U5bTZtbC94ckRuQWQrRmtTeGRyVFVxMgpRVUx6aGpXSS9IcFMwVklBeDJSNzJNcS9oZHpOQWdNQkFBR2pXVEJYTUE0R0ExVWREd0VCL3dRRUF3SUNwREFQCkJnTlZIUk1CQWY4RUJUQURBUUgvTUIwR0ExVWREZ1FXQkJScjlLODU3TmtVWHV2STMxRGY0Y0N0NjI1aDNUQVYKQmdOVkhSRUVEakFNZ2dwcmRXSmxjbTVsZEdWek1BMEdDU3FHU0liM0RRRUJDd1VBQTRJQkFRQVRndXFNN2xPdApId1BUOVlUcWdlanhRMVlnRFBNd0lQQU5KQXZObTBrSlNtYXhlQWc0OUpSWGlEeGlOcWZnNGZ0K2tPdmN6WUZ2CnlhbnhKWVZXUmllczdSeEw5Z2VsOFZwMFEzTllqSS9xN2svcEpMSWprMkY0MHRiUldqcXVvTC9TTjc3eURzU1YKWVVBYkFaVTY1VXBWOHJGK3JHRUhwSmtQQjlGNUx3VU1SaVA5S1RtU3hNaUcvUldubjJoY0JmS0ZHdERoNGE0bwpkZXlGbVlDLzlpVThCbmpJOS84OXNVQ0Q0VFZndmRrZHJ3UUhsVUpobklORWlKK0NUVnhacXU5R2owYlJLVjJECmtzSi9ML3V0RFdNdFdFRjEzYXNvbDlhbjZtdmM3U0JzVFZ0OXlGWHFjb0trTTBkVHRyeVBKNmgzS3ZPeXc1aUIKcUhDOG56MUJpRUxqCi0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://39887421528F917F64C694250BB41733.gr7.eu-west-2.eks.amazonaws.com
  name: arn:aws:eks:eu-west-2:471112983834:cluster/my-eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:eu-west-2:471112983834:cluster/my-eks-cluster
    user: arn:aws:eks:eu-west-2:471112983834:cluster/my-eks-cluster
  name: arn:aws:eks:eu-west-2:471112983834:cluster/my-eks-cluster
current-context: arn:aws:eks:eu-west-2:471112983834:cluster/my-eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:eu-west-2:471112983834:cluster/my-eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - --region
      - eu-west-2
      - eks
      - get-token
      - --cluster-name
      - my-eks-cluster
      - --output
      - json
      command: aws
